# @host = http://localhost:9999
@host = https://backend-09-server.herokuapp.com/

###

GET {{host}}/messages

###

POST {{host}}/messages
Content-Type: application/json

{
    "content": "First message"
}